name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  # Job 1: Build and Test Backend
  build-test-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker cache
        uses: actions/cache@v3
        with:
          path: /var/lib/docker
          key: ${{ runner.os }}-docker-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-docker-

      - name: Build backend container
        run: docker build -t backend:test -f Dockerfile.backend .

      - name: Run backend container for testing
        run: |
          docker network create my_network
          docker run --name mongodb --network my_network -d mongodb
          docker run --name backend --network my_network -d backend:test
          sleep 10 # Wait for services to start

      - name: Run unit tests
        run: docker exec backend npm test

      - name: Save test results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: backend-test-results
          path: ./test-results/ # Update path to your test results

      - name: Stop and remove containers
        run: |
          docker stop backend mongodb
          docker rm backend mongodb
          docker network rm my_network
 
